---
meta:
  name:    shield
  target:  pipes/shield
  url:     https://pipes.scalecf.net
  exposed: false

  initial_version: 0.6.4

  go:
    version:    "latest"
    binary:     shield
    cmd_module: ./cmd/shield

  bosh:
    target:   ((thunder-dome.url))
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cloudfoundry-community-aws.access_key_id))
    secret_key: ((cloudfoundry-community-aws.secret_access_key))

  git:
    email: ((cloudfoundry-community-ci-bot-github.email))
    name:  ((cloudfoundry-community-ci-bot-github.name))

  github:
    owner:           shieldproject
    repo:            shield
    branch:          develop
    main-branch:     main
    private_key:     ((cloudfoundry-community-ci-bot-github.private_key))
    access_token:    ((cloudfoundry-community-ci-bot-github.access_token))
    access_token_rw: ((cloudfoundry-community-ci-bot-github.access_token_rw))

  slack:
    webhook: ((slack.webhook))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))

groups:
- name: (( grab meta.pipeline ))
  jobs:
  - (( append ))
  - phalanx

